#!/bin/sh

readonly  DIST="bimodal.lua"
readonly SHORT="00300000" # ≈500 μs
readonly  LONG="30000000" # ≈50  ms

series="$1" # server part
indep="$2" # permillage of long requests
const="$3" # total num cores
name="$4" # experiment name
addr="$5" # server address

. wrk/client.sh
coregroup 0 "$const" -s"$DIST" -c2 "$URL/$SHORT" "/$LONG" "$indep" >"`logfile`" 2>&1
wait

logfile
