#!/bin/sh

series="$1" # series part
switch="$2" # command-line switch(es) (if it starts w/ a '-') or num cores (o.w.)
# total num cores is presently ignored
name="$4" # experiment name
addr="$5" # server address

case "$switch" in
-*)
	const="1"
	;;
*)
	const="$switch"
	switch="-c2"
	;;
esac

. wrk/client.sh
data="`coregroup 0 "$const" $switch "$URL/300000" 2>&1`"
wait

indep="`echo "$data" | sed -n "s|^Requests/sec:\s\+\(.\+\)\..*|\1|p" | paste -sd+ | bc`"
echo "$data" >"`logfile`"

logfile
