#!/bin/sh

if [ "$#" -lt "2" ]
then
	echo "USAGE: $0 <directory> <percentile> []"
	exit 1
fi

class=""
if [ "$#" -eq "3" ]
then
	class="$3"
fi

percentile="$2"
filename="$1_$percentile"
if [ -n "$class" ]
then
	filename="$filename-$class"
fi
filename="$filename.csv"

script="s|.*$percentile%\s\+||p"
wrapper=":figures/libsi_us.so"
if [ "$percentile" = "tput" ]
then
	script="s|^Requests/sec:\s\+||p"
	wrapper=""
fi
wrapper="LD_PRELOAD=figures/libpermille_percent.so:$wrapper"

eval export "$wrapper" >/dev/null
csv="`figures/log2csv -s "baseline$class,preempt$class" -n "$script" "$1"/*.log`"
unset LD_PRELOAD

if [ -e "$filename" ]
then
	bytes="`head -n2 "$filename" | wc -c`"
	truncate -s"$bytes" "$filename"
	echo "$csv" | tail -n+3 >>"$filename"
else
	echo "$csv" >"$filename"
fi

figures/linegraph "`echo "$filename" | sed "s/\.csv$/.png/"`" <"$filename"
