#!/bin/sh

if [ "$#" -lt "2" ]
then
	echo "USAGE: $0 <directory> <percentile> []"
	exit 1
fi

class=""
if [ "$#" -eq "3" ]
then
	class="$3"
fi

percentile="$2"
filename="$1_$percentile"
if [ -n "$class" ]
then
	filename="$filename-$class"
fi
filename="$filename.csv"

if [ ! -e "$filename" ]
then
	LD_PRELOAD=figures/libsi_us.so figures/log2csv -s "baseline$class,preempt$class" -n "s|.*$percentile%\s\+||p" "$1"/*.log >"$filename"
fi

figures/linegraph graph.png <"$filename"
