#!/bin/sh

if [ "$#" -lt "2" ]
then
	cat <<-tac
		USAGE: $0 <directory> <percentile> [class] [series]

		[class] selects a single subseries, and is only applicable to latency operation
		[series] is a comma-separated list of series to plot
	tac
	exit 1
fi

class=""
if [ "$#" -ge "3" ]
then
	class="$3"
fi

series="baseline,overhead,preempt"
if [ "$#" -eq "4" ]
then
	series="$4"
fi

percentile="$2"
filename="$1_$percentile"
if [ -n "$class" ]
then
	filename="$filename-$class"
	case "$class" in
	short)
		class="1"
		;;
	long)
		class="2"
		;;
	esac
fi
filename="$filename.csv"

script="s|^$class\s*$percentile%\s\+||p"
wrapper=":figures/libsi_us.so"
if [ "$percentile" = "tput" ]
then
	script="s|^Requests/sec:\s\+||p"
	wrapper=""
fi
wrapper="LD_PRELOAD=figures/libpermille_percent.so$wrapper"

eval export "$wrapper" >/dev/null
csv="`figures/log2csv -s "$series" -n "$script" "$1"/*.log`"
csvd="$?"
unset LD_PRELOAD
if [ "$csvd" -ne "0" ]
then
	cat >&2 <<-tac

		Hmm... maybe try running with a custom [series] set?
	tac
	exit 2
fi

if [ -e "$filename" ]
then
	bytes="`head -n2 "$filename" | wc -c`"
	truncate -s"$bytes" "$filename"
	echo "$csv" | tail -n+3 >>"$filename"
else
	echo "$csv" >"$filename"
fi

figures/linegraph "`echo "$filename" | sed "s/\.csv$/.png/"`" <"$filename"
