#!/bin/sh

readonly HELPER="client_bimodal"
readonly HELPERS="$HELPER bimodal.lua"
readonly NCLIENTCORES="14" # client
readonly MSERVERCORES="0xaaaaaaaa" # server

if [ "$#" -ne "1" ]
then
	echo "USAGE: $0 <dest dir>"
	exit 1
fi

set -eu
dir="$1" # where to store

start() {
	taskset "$MSERVERCORES" cargo run --release "$@" &
	await 1337
}

stop() {
	kill "`ps -opid -Chype | tail -n1`" && sleep 2
}

baseline() {
	set -ex
	start >&2
	ssh client "wrk/$HELPER" baseline "$@"
}

overhead() {
	set -ex
	cargo build --release
	cargo build --release --features preemptive -pinger

	export LD_PRELOAD="target/release/libinger.so"
	export LIBGOTCHA_NUMGROUPS="1"
	start >&2
	ssh client "wrk/$HELPER" overhead "$@"
}

preempt() {
	set -ex
	export LIBGOTCHA_NOGLOBALS=
	start --features preemptive >&2
	ssh client "wrk/$HELPER" preempt "$@"
}

await() {
	set +x
	local port="$1"
	while ! fuser "$port/tcp" >/dev/null 2>&1
	do
		:
	done
}

mkdir "$dir"
./version >"$dir/VERSION"

unset SSH_AUTH_SOCK
scp $HELPERS client:wrk

stop 2>/dev/null || true

for indep in `seq 0 2 20`
do
	echo "==> INDEP: `echo "$indep" | sed "s/\(.*\)\(.\)/\1.\2/;s/^\./0&/"`% long requests <=="
	for series in baseline overhead preempt
	do
		echo "   --> SERIES: $series server <--"
		until
			for file in `"$series" "$indep" "$NCLIENTCORES" "$dir"`
			do
				rsync --remove-source-files "client:wrk/$file" "$dir"
			done
			stop
		do
			:
		done
	done
done 2>&1 | tee "$dir/LOG"

cp Cargo.lock "$dir/DEPS"

echo "SUCCESS!  Results are in $dir/"
