#!/usr/bin/python3

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from itertools import cycle
from matplotlib import pyplot
from os.path import basename
from sys import argv, stdin

def main():
	linegraph = basename(argv[0]) == 'linegraph'

	url_of_sandwich = 'file:///usr/share/doc/python-matplotlib-doc/html/api/patches_api.html#matplotlib.patches.Patch.set_aa'
	if linegraph:
		url_of_sandwich = 'file:///usr/share/doc/python-matplotlib-doc/html/api/lines_api.html#matplotlib.lines.Line2D.set_aa'

	parser = ArgumentParser(epilog = 'Each line beginning with \'--\' invokes a function listed at:\n\t' + url_of_sandwich + '\non each series, cycling through the rest of the comma-separated line for the arguments.', formatter_class = RawDescriptionHelpFormatter)
	parser.add_argument('-e', action = 'store_true', help = 'Draw error bars using alternate columns')
	parser.add_argument('-l', action = 'store_true', help = 'Use log scale')
	if linegraph:
		parser.add_argument('-s', action = 'store_true', help = 'Draw a scatterplot instead of a linegraph')
	parser.add_argument('dest', help = 'Destination filename')
	args = parser.parse_args()
	errorbars = args.e
	logscale = args.l
	if linegraph:
		scatter = args.s

	title = input().strip().split(',')
	labels = input().strip().split(',')
	xlabel = labels[0]
	ylabel = title[1] if len(title) > 1 else ''
	slabels = [labels[col] for col in range(1, len(labels), 2)] if errorbars else labels[1:]
	props = {}
	data = []
	for line in stdin:
		line = line.strip().split(',')
		if line[0][:2] == '--':
			props[line[0][2:]] = cycle(line[1:])
			pass
		else:
			data.append(line)
	if linegraph:
		indeps = [float(each[0]) for each in data]
	else:
		indeps = [each[0] for each in data]
	series = [[float(col) for col in each[1:]] for each in data]
	errors = [[float(each[index]) for index in range(1, len(each), 2)] for each in series]
	if errorbars:
		series = [[float(each[col]) for col in range(0, len(each), 2)] for each in series]

	offsets = [index + 0.1 for index in range(len(data))]
	if not linegraph:
		pyplot.xticks(offsets, indeps, rotation = -45, horizontalalignment = 'left')

	rendered_series = []
	if linegraph:
		for index in range(len(series[0])):
			rendered_series.append(pyplot.errorbar(indeps, [row[index] for row in series], yerr = [row[index] for row in errors] if errorbars else None, marker = '.', linestyle = '' if scatter else '-')[0])
			if logscale:
				pyplot.yscale('log')
	else:
		rendered_series = pyplot.bar(offsets, [row[0] for row in series], log = logscale, yerr = [row[0] for row in errors] if errorbars else None)

	for rs in rendered_series:
		for prop in props:
			getattr(rs, prop)(next(props[prop]))

	if not linegraph and logscale:
		pyplot.ylim(10 ** 0, 10 ** 5)
	else:
		pyplot.ylim(0)
	pyplot.title(title[0])
	pyplot.xlabel(xlabel)
	pyplot.ylabel(ylabel)
	if len(slabels) == 1:
		pyplot.ylabel(*slabels)
	else:
		pyplot.legend(slabels)

	pyplot.savefig(args.dest, bbox_inches = 'tight')

if __name__ == '__main__':
	main()
