#!/usr/bin/python3

from argparse import ArgumentParser
from matplotlib import pyplot
from sys import stdin

def main():
	parser = ArgumentParser()
	parser.add_argument('-e', action = 'store_true', help = 'Draw error bars using alternate columns')
	parser.add_argument('-l', action = 'store_true', help = 'Use log scale')
	parser.add_argument('dest', help = 'Destination filename')
	args = parser.parse_args()
	errorbars = args.e
	logscale = args.l

	title = input().strip()
	labels = input().strip().split(',')
	xlabel = labels[0]
	slabels = [labels[col] for col in range(1, len(labels), 2)] if errorbars else labels[1:]
	data = []
	for line in stdin:
		data += [line.strip().split(',')]
	indeps = [each[0] for each in data]
	series = [[float(col) for col in each[1:]] for each in data]
	errors = [[float(each[index]) for index in range(1, len(each), 2)] for each in series]
	if errorbars:
		series = [[float(each[col]) for col in range(0, len(each), 2)] for each in series]

	offsets = [index + 0.1 for index in range(len(data))]
	# TODO: Remove these list comprehensions when adding support for multiple series:
	pyplot.title(title)
	pyplot.xlabel(xlabel)
	pyplot.ylabel(*slabels)
	pyplot.xticks(offsets, indeps, rotation = -45, horizontalalignment = 'left')
	if logscale:
		pyplot.ylim(10 ** 0, 10 ** 5)
	graph = pyplot.bar(offsets, [row[0] for row in series], log = logscale, yerr = [row[0] for row in errors] if errorbars else None)

	pyplot.savefig(args.dest, bbox_inches = 'tight')

if __name__ == '__main__':
	main()
